Pick different struct name if Reflex dictionary is split (ROOT6)
There are 5 packages, which are built in a few chunks in order
to have smaller translation unit and deliver finer granularity.

All chunks are linked together back into a single Reflex dictionary.
In ROOT6 it still has multiple intialization points, and 'struct
dictionary' from anonymous namespace is executed. In ROOT6 it's
done in the same context and causes multiple redefinitions:

input_line_35:60:10: error: redefinition of 'dictionary'
 struct dictionary {
        ^
input_line_19:99:10: note: previous definition is here
 struct dictionary {
        ^
input_line_37:73:10: error: redefinition of 'dictionary'
 struct dictionary {
        ^
input_line_19:99:10: note: previous definition is here
 struct dictionary {
        ^
Rename structs in each classes_*.h to avoid such conflicts in
ROOT6.

If Reflex dictionary is built in a few chunks, each chunk has to
have a unique struct name (if used).

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>